server {
    listen 443 ssl;
    server_name my-domain.com;

    ssl_certificate /path-to-certs/fullchain.pem;
    ssl_certificate_key /path-to-certs/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Запрет индексации поисковиками
    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive" always;

    # Апишка бэкенда
    location /api {
        proxy_pass http://localhost:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Websockets
    location /ws {
        proxy_pass http://localhost:8085;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # Todo: Фронтенд
    location / {
        
    }
}
